package Logic;
// Generated 07.12.2017 16:40:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Achievements generated by hbm2java
 */
@Entity
@Table(name="achievements"
    ,catalog="sqltraining"
)
public class Achievements  implements java.io.Serializable {


     private Integer idAchievements;
     private Lecture lecture;
     private Users users;
     private int eval;
     private boolean status;

    public Achievements() {
    }

    public Achievements(Lecture lecture, Users users, int eval, boolean status) {
       this.lecture = lecture;
       this.users = users;
       this.eval = eval;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_achievements", unique=true, nullable=false)
    public Integer getIdAchievements() {
        return this.idAchievements;
    }
    
    public void setIdAchievements(Integer idAchievements) {
        this.idAchievements = idAchievements;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_lecture", nullable=false)
    public Lecture getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Lecture lecture) {
        this.lecture = lecture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_users", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="eval", nullable=false)
    public int getEval() {
        return this.eval;
    }
    
    public void setEval(int eval) {
        this.eval = eval;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


