package Logic;
// Generated 07.12.2017 16:40:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name="answer"
    ,catalog="sqltraining"
)
public class Answer  implements java.io.Serializable {


     private Integer idAnswer;
     private Question question;
     private String answer;
     private boolean correct;

    public Answer() {
    }

    public Answer(Question question, String answer, boolean correct) {
       this.question = question;
       this.answer = answer;
       this.correct = correct;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_answer", unique=true, nullable=false)
    public Integer getIdAnswer() {
        return this.idAnswer;
    }
    
    public void setIdAnswer(Integer idAnswer) {
        this.idAnswer = idAnswer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_question", nullable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }

    
    @Column(name="answer", nullable=false, length=65535)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    
    @Column(name="correct", nullable=false)
    public boolean isCorrect() {
        return this.correct;
    }
    
    public void setCorrect(boolean correct) {
        this.correct = correct;
    }




}


