package Logic;
// Generated 07.12.2017 16:40:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Authusers generated by hbm2java
 */
@Entity
@Table(name="authusers"
    ,catalog="sqltraining"
)
public class Authusers  implements java.io.Serializable {


     private Integer idAuth;
     private Users users;
     private String mac;

    public Authusers() {
    }

    public Authusers(Users users, String mac) {
       this.users = users;
       this.mac = mac;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_auth", unique=true, nullable=false)
    public Integer getIdAuth() {
        return this.idAuth;
    }
    
    public void setIdAuth(Integer idAuth) {
        this.idAuth = idAuth;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_users", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="MAC", nullable=false, length=20)
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }




}


