package Logic;
// Generated 07.12.2017 16:40:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lecture generated by hbm2java
 */
@Entity
@Table(name="lecture"
    ,catalog="sqltraining"
)
public class Lecture  implements java.io.Serializable {


     private Integer idLecture;
     private Users users;
     private String name;
     private String lecture;
     private Set<Achievements> achievementses = new HashSet<Achievements>(0);
     private Set<Question> questions = new HashSet<Question>(0);

    public Lecture() {
    }

	
    public Lecture(Users users, String name, String lecture) {
        this.users = users;
        this.name = name;
        this.lecture = lecture;
    }
    public Lecture(Users users, String name, String lecture, Set<Achievements> achievementses, Set<Question> questions) {
       this.users = users;
       this.name = name;
       this.lecture = lecture;
       this.achievementses = achievementses;
       this.questions = questions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_lecture", unique=true, nullable=false)
    public Integer getIdLecture() {
        return this.idLecture;
    }
    
    public void setIdLecture(Integer idLecture) {
        this.idLecture = idLecture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_users", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="name", nullable=false, length=65535)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="lecture", nullable=false, length=65535)
    public String getLecture() {
        return this.lecture;
    }
    
    public void setLecture(String lecture) {
        this.lecture = lecture;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lecture")
    public Set<Achievements> getAchievementses() {
        return this.achievementses;
    }
    
    public void setAchievementses(Set<Achievements> achievementses) {
        this.achievementses = achievementses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lecture")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }




}


