package Logic;
// Generated 07.12.2017 16:40:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="sqltraining"
)
public class Users  implements java.io.Serializable {


     private Integer idUsers;
     private String firstname;
     private String lastname;
     private String username;
     private String password;
     private String typeUsers;
     private Set<Authusers> authuserses = new HashSet<Authusers>(0);
     private Set<Lecture> lectures = new HashSet<Lecture>(0);
     private Set<Achievements> achievementses = new HashSet<Achievements>(0);

    public Users() {
    }

	
    public Users(String firstname, String lastname, String username, String password, String typeUsers) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.username = username;
        this.password = password;
        this.typeUsers = typeUsers;
    }
    public Users(String firstname, String lastname, String username, String password, String typeUsers, Set<Authusers> authuserses, Set<Lecture> lectures, Set<Achievements> achievementses) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.username = username;
       this.password = password;
       this.typeUsers = typeUsers;
       this.authuserses = authuserses;
       this.lectures = lectures;
       this.achievementses = achievementses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_users", unique=true, nullable=false)
    public Integer getIdUsers() {
        return this.idUsers;
    }
    
    public void setIdUsers(Integer idUsers) {
        this.idUsers = idUsers;
    }

    
    @Column(name="firstname", nullable=false, length=65535)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", nullable=false, length=65535)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="username", nullable=false, length=65535)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="type_users", nullable=false, length=5)
    public String getTypeUsers() {
        return this.typeUsers;
    }
    
    public void setTypeUsers(String typeUsers) {
        this.typeUsers = typeUsers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Authusers> getAuthuserses() {
        return this.authuserses;
    }
    
    public void setAuthuserses(Set<Authusers> authuserses) {
        this.authuserses = authuserses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Lecture> getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set<Lecture> lectures) {
        this.lectures = lectures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Achievements> getAchievementses() {
        return this.achievementses;
    }
    
    public void setAchievementses(Set<Achievements> achievementses) {
        this.achievementses = achievementses;
    }




}


