package logic;
// Generated 03.06.2017 18:49:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Intermediatestops generated by hbm2java
 */
@Entity
@Table(name="intermediatestops"
    ,catalog="bustickets"
)
public class Intermediatestops  implements java.io.Serializable {


     private Integer idStops;
     private Route route;
     private String nameOfStop;

    public Intermediatestops() {
    }

    public Intermediatestops(Route route, String nameOfStop) {
       this.route = route;
       this.nameOfStop = nameOfStop;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_stops", unique=true, nullable=false)
    public Integer getIdStops() {
        return this.idStops;
    }
    
    public void setIdStops(Integer idStops) {
        this.idStops = idStops;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_route", nullable=false)
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    
    @Column(name="nameOfStop", nullable=false, length=100)
    public String getNameOfStop() {
        return this.nameOfStop;
    }
    
    public void setNameOfStop(String nameOfStop) {
        this.nameOfStop = nameOfStop;
    }




}


