package logic;
// Generated 03.06.2017 18:49:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name="route"
    ,catalog="bustickets"
)
public class Route  implements java.io.Serializable {


     private Integer idRoute;
     private String start;
     private String end;
     private int countOfseats;
     private Date dateStart;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<Intermediatestops> intermediatestopses = new HashSet<Intermediatestops>(0);
     private Set<Seats> seatses = new HashSet<Seats>(0);

    public Route() {
    }

	
    public Route(String start, String end, int countOfseats, Date dateStart) {
        this.start = start;
        this.end = end;
        this.countOfseats = countOfseats;
        this.dateStart = dateStart;
    }
    public Route(String start, String end, int countOfseats, Date dateStart, Set<Review> reviews, Set<Intermediatestops> intermediatestopses, Set<Seats> seatses) {
       this.start = start;
       this.end = end;
       this.countOfseats = countOfseats;
       this.dateStart = dateStart;
       this.reviews = reviews;
       this.intermediatestopses = intermediatestopses;
       this.seatses = seatses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_route", unique=true, nullable=false)
    public Integer getIdRoute() {
        return this.idRoute;
    }
    
    public void setIdRoute(Integer idRoute) {
        this.idRoute = idRoute;
    }

    
    @Column(name="start", nullable=false, length=100)
    public String getStart() {
        return this.start;
    }
    
    public void setStart(String start) {
        this.start = start;
    }

    
    @Column(name="end", nullable=false, length=100)
    public String getEnd() {
        return this.end;
    }
    
    public void setEnd(String end) {
        this.end = end;
    }

    
    @Column(name="countOfseats", nullable=false)
    public int getCountOfseats() {
        return this.countOfseats;
    }
    
    public void setCountOfseats(int countOfseats) {
        this.countOfseats = countOfseats;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateStart", nullable=false, length=10)
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<Intermediatestops> getIntermediatestopses() {
        return this.intermediatestopses;
    }
    
    public void setIntermediatestopses(Set<Intermediatestops> intermediatestopses) {
        this.intermediatestopses = intermediatestopses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="route")
    public Set<Seats> getSeatses() {
        return this.seatses;
    }
    
    public void setSeatses(Set<Seats> seatses) {
        this.seatses = seatses;
    }




}


