package logic;
// Generated 03.06.2017 18:49:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seats generated by hbm2java
 */
@Entity
@Table(name="seats"
    ,catalog="bustickets"
)
public class Seats  implements java.io.Serializable {


     private Integer idSeat;
     private Route route;
     private boolean status;
     private int seatNomber;
     private Set<Tickets> ticketses = new HashSet<Tickets>(0);

    public Seats() {
    }

	
    public Seats(Route route, boolean status, int seatNomber) {
        this.route = route;
        this.status = status;
        this.seatNomber = seatNomber;
    }
    public Seats(Route route, boolean status, int seatNomber, Set<Tickets> ticketses) {
       this.route = route;
       this.status = status;
       this.seatNomber = seatNomber;
       this.ticketses = ticketses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_seat", unique=true, nullable=false)
    public Integer getIdSeat() {
        return this.idSeat;
    }
    
    public void setIdSeat(Integer idSeat) {
        this.idSeat = idSeat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_route", nullable=false)
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="seatNomber", nullable=false)
    public int getSeatNomber() {
        return this.seatNomber;
    }
    
    public void setSeatNomber(int seatNomber) {
        this.seatNomber = seatNomber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="seats")
    public Set<Tickets> getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set<Tickets> ticketses) {
        this.ticketses = ticketses;
    }




}


