package logic;
// Generated 03.06.2017 18:49:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */
@Entity
@Table(name="tickets"
    ,catalog="bustickets"
)
public class Tickets  implements java.io.Serializable {


     private Integer idTickets;
     private Seats seats;
     private int price;
     private String fullName;
     private String documents;

    public Tickets() {
    }

    public Tickets(Seats seats, int price, String fullName, String documents) {
       this.seats = seats;
       this.price = price;
       this.fullName = fullName;
       this.documents = documents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_tickets", unique=true, nullable=false)
    public Integer getIdTickets() {
        return this.idTickets;
    }
    
    public void setIdTickets(Integer idTickets) {
        this.idTickets = idTickets;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seatNomber", nullable=false)
    public Seats getSeats() {
        return this.seats;
    }
    
    public void setSeats(Seats seats) {
        this.seats = seats;
    }

    
    @Column(name="price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }

    
    @Column(name="fullName", nullable=false, length=150)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="documents", nullable=false, length=30)
    public String getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(String documents) {
        this.documents = documents;
    }




}


