/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import DAO.Factory;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logic.Intermediatestops;
import logic.Route;
import logic.Seats;
import logic.Tickets;

/**
 *
 * @author Admin
 */
public class BusTicket extends javax.swing.JFrame {

    /**
     * Creates new form BusTicket
     */
    ArrayList<Integer> ID = new ArrayList<Integer>();
    List<Boolean> status = new ArrayList<>();
    List<Integer> ID_seat = new ArrayList<Integer>();
    DefaultTableModel dtm = new DefaultTableModel(); 
    int clicked_name = 0;
    String tr = null;
    int cls = 0;
    public BusTicket() {
        initComponents();
        dtm.addColumn("Status");
        dtm.addColumn("Nomber");
        setTitle("Bus Tickets");
        this.setLocation(650, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StartPoint = new javax.swing.JTextField();
        EndPoint = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RouteCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        FullName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DocumentUser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Start Point:");

        jLabel2.setText("End Point:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RouteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        RouteCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RouteComboItemStateChanged(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("FullName:");

        jLabel4.setText("Document:");

        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("AddReviev");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RouteCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(StartPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(EndPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DocumentUser)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RouteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DocumentUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String starts = StartPoint.getText();
            String ends = EndPoint.getText();
            ID.clear();
            RouteCombo.removeAllItems();
            Collection endPo = Factory.getInstance().getInterDAO().getIntermStopsOf(ends);
            if(!endPo.isEmpty())
            {
                Iterator it = endPo.iterator();
                while(it.hasNext())
                {
                    Intermediatestops endPoi = (Intermediatestops) it.next();
              //      System.out.println(endPoi.getRoute().getIdRoute()+"=========All Intermed of "+endPoi.getNameOfStop());
                    ID.add(endPoi.getRoute().getIdRoute());
                    Collection routeTO = Factory.getInstance().getRouteDAO().getRouteTo(starts, endPoi);
                    Iterator it2 = routeTO.iterator();
                    while(it2.hasNext())
                    {
                        Route rout = (Route) it2.next();
                        RouteCombo.addItem(rout.getStart()+" "+rout.getEnd() + " "+rout.getDateStart());
                        
                       // System.out.println("Starts: "+rout.getStart()+" END "+rout.getEnd() + " Date "+rout.getDateStart());
                    }
                }
            }
            else
            {   
                RouteCombo.removeAllItems();
                Collection endss = Factory.getInstance().getRouteDAO().getEndRoute(starts, ends);
                Iterator it3 = endss.iterator();
                
                    while(it3.hasNext())
                        {
                            Route fRoute = (Route) it3.next();
                            ID.add(fRoute.getIdRoute());
                           // System.out.println(fRoute.getIdRoute()+"=========All Intermed of "+ fRoute.getStart()+" "+fRoute.getEnd() + " "+fRoute.getDateStart());
                            RouteCombo.addItem(fRoute.getStart()+" "+fRoute.getEnd() + " "+fRoute.getDateStart());
                            
                        }
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void getRouteIn()
    {
        ID_seat.clear();
        while (dtm.getRowCount() > 0)  dtm.removeRow(0);
        try {
                    int index = RouteCombo.getSelectedIndex();
                    tr = (String) RouteCombo.getSelectedItem();
                    Collection emptySeat = Factory.getInstance().getSeatDAO().getSeatsByRoute(ID.get(index));
                    Iterator it = emptySeat.iterator();
                    while(it.hasNext())
                    {
                        Seats empSeat = (Seats) it.next();
                        if(empSeat.isStatus()== false){
                          dtm.addRow(new Object[]{empSeat.isStatus(),empSeat.getSeatNomber()});
                          ID_seat.add(empSeat.getIdSeat());
                        }
                        
                        //System.out.println(empSeat.isStatus()+" Nomber: "+empSeat.getSeatNomber());
                        status.add(empSeat.isStatus());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTable1.setModel(dtm);
    }
    private void RouteComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RouteComboItemStateChanged
        ID_seat.clear();
        while (dtm.getRowCount() > 0)  dtm.removeRow(0);
        if (RouteCombo.getItemCount() >= 0)  {
            if (evt.getStateChange()==ItemEvent.SELECTED) 
            {
                
                getRouteIn();
                
            }
    }
    }//GEN-LAST:event_RouteComboItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            int num;
            num = jTable1.rowAtPoint(evt.getPoint());
            clicked_name = (int) jTable1.getValueAt(num, 1);
            cls =  jTable1.getSelectedRow();
            System.out.println(clicked_name +"      "+cls);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {                                         
            String fn = FullName.getText();
            String dc = DocumentUser.getText();
            
            int id_s = ID_seat.get(cls);
            Collection findUser = Factory.getInstance().getTicketDAO().getInfoByDoc(Integer.parseInt(dc));
            if(!findUser.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "You already have a ticket ", "Error ", JOptionPane.OK_OPTION);
                //System.out.println("Yes");
            }
            else
                {
                    Seats s11 = Factory.getInstance().getSeatDAO().getSeatByID(ID_seat.get(cls));
                    if(s11.isStatus() == true)
                    {
                        JOptionPane.showMessageDialog(null, "This place has already been booked", "Error ", JOptionPane.OK_OPTION);
                        getRouteIn();
                    }
                    else
                    {
                     Tickets tickets = new Tickets();
       //            Collection seatss = Factory.getInstance().getSeatDAO().getSeatsByID(ID_seat.get(cls));
       //            Iterator it = seatss.iterator();
       //            while(it.hasNext())
       //            {
       //                Seats seat = (Seats) it.next();

                      tickets.setFullName(fn);
                       tickets.setDocuments(dc);
                       tickets.setPrice((5*80));
                       tickets.setSeats(s11);
       //            }
                       Factory.getInstance().getTicketDAO().addTickets(tickets);
                       try {
                           Factory.getInstance().getSeatDAO().updateSeats(id_s, true);

                       } catch (SQLException ex) {
                           Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
                       }
       //                    nomberID.setText("123");
       //                    seatNombers.setText(""+clicked_name);
       //                    prices.setText(" "+2*50);
       //                    fullNames.setText(fn);
       //                    document.setText(dc);
       //                    routeTick.setText(tr);
       //                    dateStart.setText(tr);
                    }
                      
            }
            System.out.println(ID_seat.get(cls));
        } catch (SQLException ex) {
            Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                    this.setVisible(false);
                    AddReview addR = new AddReview();
                    addR.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DocumentUser;
    private javax.swing.JTextField EndPoint;
    private javax.swing.JTextField FullName;
    private javax.swing.JComboBox<String> RouteCombo;
    private javax.swing.JTextField StartPoint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
