/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticket;

import DAO.Factory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logic.Intermediatestops;
import logic.Route;
import logic.Seats;
import logic.Tickets;

/**
 *
 * @author Admin
 */
public class TestForm extends javax.swing.JFrame {

    /**
     * Creates new form TestForm
     */
    ArrayList<Integer> ID = new ArrayList<Integer>();
    List<Boolean> status = new ArrayList<>();
    List<Integer> ID_seat = new ArrayList<Integer>();
    DefaultTableModel dtm = new DefaultTableModel(); 
    int clicked_name = 0;
    String tr = null;
    int cls = 0;
    public TestForm() {
        initComponents();
        dtm.addColumn("Status");
        dtm.addColumn("Nomber");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        startPoint = new javax.swing.JTextField();
        endPoint = new javax.swing.JTextField();
        routess = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomberID = new javax.swing.JLabel();
        seatNombers = new javax.swing.JLabel();
        prices = new javax.swing.JLabel();
        fullNames = new javax.swing.JLabel();
        document = new javax.swing.JLabel();
        routeTick = new javax.swing.JLabel();
        dateStart = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("GetAllIntermidate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GetFullRoute");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("GetRouteTo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        routess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        routess.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                routessItemStateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Buy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomber:");

        jLabel2.setText("SeatNomber:");

        jLabel3.setText("Price:");

        jLabel4.setText("FullName:");

        jLabel5.setText("Document:");

        jLabel6.setText("Route:");

        jLabel7.setText("Date:");

        nomberID.setText("jLabel8");

        seatNombers.setText("jLabel8");

        prices.setText("jLabel8");

        fullNames.setText("jLabel8");

        document.setText("jLabel8");

        routeTick.setText("jLabel8");

        dateStart.setText("jLabel8");

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(routess, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(startPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(endPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(38, 38, 38)
                                    .addComponent(nomberID))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateStart)
                                    .addComponent(routeTick)
                                    .addComponent(document)
                                    .addComponent(fullNames)
                                    .addComponent(prices)
                                    .addComponent(seatNombers))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(startPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(routess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomberID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(seatNombers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(prices))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fullNames))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(document))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(routeTick))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dateStart))
                        .addGap(60, 60, 60)
                        .addComponent(jButton5)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Collection allInter = Factory.getInstance().getInterDAO().getAllIntermStops();
            Iterator it = allInter.iterator();
            System.out.println("=========All Intermed=========");
            while(it.hasNext()){
                Intermediatestops intem = (Intermediatestops) it.next();
                System.out.println("NameOfStop: "+intem.getNameOfStop() + "    ID:"+intem.getIdStops());
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<String> list = new ArrayList<String>();
        ArrayList<Integer> ID = new ArrayList<Integer>();
        try {
            Collection allInter = Factory.getInstance().getInterDAO().getAllIntermStops();
            Iterator it = allInter.iterator();
            while(it.hasNext()){
                try {
                    Intermediatestops intem = (Intermediatestops) it.next();
                   // System.out.println("NameOfStop: "+intem.getNameOfStop() + "    ID:"+intem.getIdStops());
                    Collection fullRoute  = Factory.getInstance().getRouteDAO().getFullRoute(intem);
                    Iterator it2 = fullRoute.iterator();
                    while(it2.hasNext()){
                        Route route = (Route) it2.next();
                        //System.out.println("=========All Intermed of "+route.getStart()+"========="+route.getEnd());
                        list.add(route.getIdRoute()+" "+route.getStart()+" "+intem.getNameOfStop());
                        ID.add(route.getIdRoute());
                    }
                 //   System.out.println("NameOfStop: "+intem.getNameOfStop() + "    ID:"+intem.getIdStops());
                } catch (SQLException ex) {
                    Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
            for(String o : list) {
                if(o.equals("Sofia Plovdiv")){
                    System.out.println("ID: "+ID+"Route:" + o);
                }
            
        }
        } catch (SQLException ex) {
            Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String starts = startPoint.getText();
            String ends = endPoint.getText();
            ID.clear();
            routess.removeAllItems();
            Collection endPo = Factory.getInstance().getInterDAO().getIntermStopsOf(ends);
            if(!endPo.isEmpty())
            {
                Iterator it = endPo.iterator();
                while(it.hasNext())
                {
                    Intermediatestops endPoi = (Intermediatestops) it.next();
              //      System.out.println(endPoi.getRoute().getIdRoute()+"=========All Intermed of "+endPoi.getNameOfStop());
                    ID.add(endPoi.getRoute().getIdRoute());
                    Collection routeTO = Factory.getInstance().getRouteDAO().getRouteTo(starts, endPoi);
                    Iterator it2 = routeTO.iterator();
                    while(it2.hasNext())
                    {
                        Route rout = (Route) it2.next();
                        routess.addItem(rout.getStart()+" "+rout.getEnd() + " "+rout.getDateStart());
                        
                       // System.out.println("Starts: "+rout.getStart()+" END "+rout.getEnd() + " Date "+rout.getDateStart());
                    }
                }
            }
            else
            {   routess.removeAllItems();
                Collection endss = Factory.getInstance().getRouteDAO().getEndRoute(starts, ends);
                Iterator it3 = endss.iterator();
                
                    while(it3.hasNext())
                        {
                            Route fRoute = (Route) it3.next();
                            ID.add(fRoute.getIdRoute());
                           // System.out.println(fRoute.getIdRoute()+"=========All Intermed of "+ fRoute.getStart()+" "+fRoute.getEnd() + " "+fRoute.getDateStart());
                            routess.addItem(fRoute.getStart()+" "+fRoute.getEnd() + " "+fRoute.getDateStart());
                            
                        }
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void routessItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_routessItemStateChanged
        ID_seat.clear();
        while (dtm.getRowCount() > 0)  dtm.removeRow(0);
        if (routess.getItemCount() >= 0)  {
            if (evt.getStateChange()==ItemEvent.SELECTED) 
            {
                try {
                    int index = routess.getSelectedIndex();
                    tr = (String) routess.getSelectedItem();
                    Collection emptySeat = Factory.getInstance().getSeatDAO().getSeatsByRoute(ID.get(index));
                    Iterator it = emptySeat.iterator();
                    while(it.hasNext())
                    {
                        Seats empSeat = (Seats) it.next();
                        if(empSeat.isStatus()== false){
                          dtm.addRow(new Object[]{empSeat.isStatus(),empSeat.getSeatNomber()});
                          ID_seat.add(empSeat.getIdSeat());
                        }
                        
                        //System.out.println(empSeat.isStatus()+" Nomber: "+empSeat.getSeatNomber());
                        status.add(empSeat.isStatus());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTable1.setModel(dtm);
                
                
            }
    }
    }//GEN-LAST:event_routessItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int num;
        num = jTable1.rowAtPoint(evt.getPoint());
        clicked_name = (int) jTable1.getValueAt(num, 1);
        cls =  jTable1.getSelectedRow();
        System.out.println(clicked_name +"      "+cls);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {                                         
            String fn = jt1.getText();
            String dc = jt2.getText();
            
            int id_s = ID_seat.get(cls);
            Collection findUser = Factory.getInstance().getTicketDAO().getInfoByDoc(Integer.parseInt(dc));
            if(!findUser.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "You already have a ticket ", "Error ", JOptionPane.OK_OPTION);
                //System.out.println("Yes");
            }
            else
                {
            Tickets tickets = new Tickets();
//            Collection seatss = Factory.getInstance().getSeatDAO().getSeatsByID(ID_seat.get(cls));
//            Iterator it = seatss.iterator();
//            while(it.hasNext())
//            {
//                Seats seat = (Seats) it.next();
                Seats s11 = Factory.getInstance().getSeatDAO().getSeatByID(ID_seat.get(cls));
                tickets.setFullName(fn);
                tickets.setDocuments(dc);
                tickets.setPrice((5*80));
                tickets.setSeats(s11);
//            }
                Factory.getInstance().getTicketDAO().addTickets(tickets);
                try {
                    Factory.getInstance().getSeatDAO().updateSeats(id_s, true);

                } catch (SQLException ex) {
                    Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    nomberID.setText("123");
                    seatNombers.setText(""+clicked_name);
                    prices.setText(" "+2*50);
                    fullNames.setText(fn);
                    document.setText(dc);
                    routeTick.setText(tr);
                    dateStart.setText(tr);
            }
            System.out.println(ID_seat.get(cls));
        } catch (SQLException ex) {
            Logger.getLogger(TestForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateStart;
    private javax.swing.JLabel document;
    private javax.swing.JTextField endPoint;
    private javax.swing.JLabel fullNames;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JLabel nomberID;
    private javax.swing.JLabel prices;
    private javax.swing.JLabel routeTick;
    private javax.swing.JComboBox<String> routess;
    private javax.swing.JLabel seatNombers;
    private javax.swing.JTextField startPoint;
    // End of variables declaration//GEN-END:variables
}
