/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqltraining;

import DAO.Factory;
import Logic.Achievements;
import Logic.Authusers;
import Logic.Users;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainMenu extends javax.swing.JFrame {
    Integer ID = 0;
    String mac = null;
    String type = null;
    Integer ID_u = null;
    ArrayList<Boolean> achivment = new ArrayList<Boolean>();
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        //String mac = Mac();
        uSetting.setVisible(false);
        themsButton.setFocusPainted(false);
        Collection userForMac = Factory.getInstance().getAuthUserDAO().findByMAC(Mac());
        
        Iterator it = userForMac.iterator();
        while(it.hasNext())
        {
            Authusers authUsers = (Authusers) it.next();
            
            Collection userInfo = Factory.getInstance().getUserDAO().getAuthUserInfo(authUsers);
            Iterator it2 = userInfo.iterator();
            while(it2.hasNext())
            {
                Users users = (Users) it2.next();
                ID_u = users.getIdUsers();
                wText.setText(""+users.getFirstname()+" "+users.getLastname());
                ID = authUsers.getIdAuth();
                type = users.getTypeUsers();
                
                if(users.getTypeUsers().equals("admin"))
                {
                    uSetting.setVisible(true);
                }
                else
                {
                    uSetting.setVisible(false);
                }
                
                System.out.print(ID);
            }
        }
    }


    public static String Mac()
        {
        String macA = null;
        try {
            InetAddress ip;
            
            ip = InetAddress.getLocalHost();
            NetworkInterface network;
            
            try {
                network = NetworkInterface.getByInetAddress(ip);
                byte[] mac = network.getHardwareAddress();
            
                //System.out.print("Current MAC address : ");

                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < mac.length; i++) {
                    sb.append(String.format("%02X%s", mac[i], (i < mac.length - 1) ? "-" : ""));
                }
                macA = sb.toString();
            } catch (SocketException ex) {
                Logger.getLogger(SQLTraining.class.getName()).log(Level.SEVERE, null, ex);
            } 
        } catch (UnknownHostException ex) {
            Logger.getLogger(SQLTraining.class.getName()).log(Level.SEVERE, null, ex);
        }
        return macA;
           
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menupanel = new javax.swing.JPanel();
        themsButton = new javax.swing.JButton();
        statisticButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        wText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        wText1 = new javax.swing.JLabel();
        uSetting = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setLocation(new java.awt.Point(400, 500));
        setUndecorated(true);
        setResizable(false);

        welcome.setBackground(new java.awt.Color(248, 148, 6));
        welcome.setMaximumSize(new java.awt.Dimension(152, 70));
        welcome.setMinimumSize(new java.awt.Dimension(152, 70));
        welcome.setPreferredSize(new java.awt.Dimension(152, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Main Menu");

        jButton1.setBackground(new java.awt.Color(248, 148, 6));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(248, 148, 6));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("_");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcomeLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(welcomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        menupanel.setBackground(new java.awt.Color(44, 62, 80));
        menupanel.setMaximumSize(new java.awt.Dimension(414, 394));
        menupanel.setMinimumSize(new java.awt.Dimension(414, 394));
        menupanel.setPreferredSize(new java.awt.Dimension(414, 400));

        themsButton.setBackground(new java.awt.Color(34, 167, 240));
        themsButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        themsButton.setForeground(new java.awt.Color(255, 255, 255));
        themsButton.setText("THEMES");
        themsButton.setBorderPainted(false);
        themsButton.setFocusable(false);
        themsButton.setPreferredSize(new java.awt.Dimension(80, 25));
        themsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themsButtonActionPerformed(evt);
            }
        });

        statisticButton.setBackground(new java.awt.Color(34, 167, 240));
        statisticButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statisticButton.setForeground(new java.awt.Color(255, 255, 255));
        statisticButton.setText("STATISTIC");
        statisticButton.setBorderPainted(false);
        statisticButton.setFocusable(false);
        statisticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(242, 38, 19));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("LOGOUT");
        exitButton.setBorderPainted(false);
        exitButton.setFocusable(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        wText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wText.setForeground(new java.awt.Color(255, 255, 255));
        wText.setText("Text");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/userIcon.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setEnabled(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(30, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(270, 225));

        wText1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        wText1.setForeground(new java.awt.Color(255, 255, 255));
        wText1.setText("Welcome:");

        uSetting.setBackground(new java.awt.Color(44, 62, 80));
        uSetting.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        uSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/settingsIcon.png"))); // NOI18N
        uSetting.setBorderPainted(false);
        uSetting.setFocusPainted(false);
        uSetting.setMargin(new java.awt.Insets(0, 0, 0, 0));
        uSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menupanelLayout.createSequentialGroup()
                                .addComponent(wText1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uSetting))
                            .addComponent(wText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statisticButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(themsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wText1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uSetting, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wText)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addComponent(themsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statisticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void themsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themsButtonActionPerformed
                 this.dispose();
                 MainFrame mf = new MainFrame("thems");
                 mf.setVisible(true);
    }//GEN-LAST:event_themsButtonActionPerformed

    private void statisticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticButtonActionPerformed
        achivment.clear();
        
        Collection achThems = Factory.getInstance().getAchievementsDAO().getAchForUser(ID_u);
           Iterator iterat = achThems.iterator();
                while(iterat.hasNext())
                    {
                        Achievements achU = (Achievements) iterat.next();
                        achivment.add(achU.isStatus());
                    }
        
         switch(type)
         {
             case "admin":
                    this.dispose();
                   MainFrame mf = new MainFrame("statistic");
                   mf.setVisible(true); 
             break;
             case "teach":
                    this.dispose();
                   MainFrame mT = new MainFrame("statistic");
                   mT.setVisible(true); 
                 break;
             case "user":
                 
                    System.out.println(ID+" "+achivment.toString());
                    if(achivment.size()<2)
                    {
                        JOptionPane.showMessageDialog(null, "You must complete at least 2 lectures to see statistics", "Message", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                         this.dispose();
                         MainFrame mf1 = new MainFrame("statistic");
                         mf1.setVisible(true); 
                    }
                 break;
         }
    }//GEN-LAST:event_statisticButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
            Factory.getInstance().getAuthUserDAO().Delete(ID);
            this.dispose();
            Authoruzation au = new Authoruzation();
            au.setVisible(true);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uSettingActionPerformed
            this.dispose();
            userSettings us = new userSettings();
            us.setVisible(true);
    }//GEN-LAST:event_uSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel menupanel;
    private javax.swing.JButton statisticButton;
    private javax.swing.JButton themsButton;
    private javax.swing.JButton uSetting;
    private javax.swing.JLabel wText;
    private javax.swing.JLabel wText1;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
